sudo: required
language: generic

services:
  - docker

before_install: 
  - docker build -t mesghali/docker-react -f Dockerfile.dev .

script:
  - docker run mesghali/docker-react npm run test -- --coverage